#!/usr/bin/env bash
set -e

plugin_dir="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/plugins"
mkdir -p "$plugin_dir"

plugins=(
  "tmux-plugins/tmux-sensible"
  "christoomey/vim-tmux-navigator"
  "tmux-plugins/tmux-yank"
  "janoamaral/tokyo-night-tmux"
)

for plugin in "${plugins[@]}"; do
  name="${plugin##*/}"
  dest="$plugin_dir/$name"
  if [ ! -d "$dest" ]; then
    git clone --depth 1 "https://github.com/$plugin" "$dest"
  fi
done
