os:
  editPreset: 'nvim-remote'
git:
  overrideGpg: true
customCommands:
  - key: 'n'
    context: 'worktrees'
    description: 'Create a new worktree session'
    prompts:
      - type: 'input'
        title: 'What is the new worktree session name?'
        key: 'WorktreeName'
        initialValue: ''
      - type: 'input'
        title: 'What is the prefix for the new worktree branch?'
        key: 'BranchPrefix'
        initialValue: 'ep/'
    command: "WORKTREE_PREFIX={{.Form.BranchPrefix}} worktree-manager add {{.Form.WorktreeName}}; tmux-sessionizer $HOME/code/postie/letterpress-app/{{.Form.WorktreeName}}; kill-lazygit-windows"
    loadingText: 'Creating worktree session'
  - key: 'd'
    context: 'worktrees'
    description: 'Delete a worktree session'
    prompts:
      - type: 'input'
        title: 'What is the prefix for the worktree branch?'
        key: 'BranchPrefix'
        initialValue: 'ep/'
    command: "WORKTREE_PREFIX={{.Form.BranchPrefix}} worktree-manager remove {{.SelectedWorktree.Name}}; tmux has-session -t {{.SelectedWorktree.Name}} 2>/dev/null && tmux kill-session -t {{.SelectedWorktree.Name}}"
    loadingText: 'Removing worktree session'
  - key: 'p'
    context: 'worktrees'
    description: 'Submit a PR'
    prompts:
      - type: 'input'
        title: 'What is the title of this PR?'
        key: 'PRTitle'
        initialValue: ''
      - type: 'input'
        title: 'Who should review this PR? (njm,swlkr,daviswahl,BryceFrye,neddenriep,gorilla076)'
        key: 'Reviewers'
        initialValue: 'njm'
    command: "gh pr create --title '{{.Form.PRTitle}}' --body-file=tmp/prs/{{.SelectedWorktree.Name}}.md --reviewer {{.Form.Reviewers}}"
    loadingText: 'Submitting a Pull Request'
