os:
  editPreset: 'nvim-remote'
customCommands:
  - key: 'n'
    context: 'worktrees'
    description: 'Create a new worktree session'
    prompts:
      - type: 'input'
        title: 'What is the new worktree session name?'
        key: 'WorktreeName'
        initialValue: ''
    command: "worktree-manager add {{.Form.WorktreeName}}; tmux-sessionizer $HOME/code/postie/letterpress-app/{{.Form.WorktreeName}}"
    loadingText: 'Creating worktree session'
  - key: 'd'
    context: 'worktrees'
    description: 'Delete a worktree session'
    command: "worktree-manager remove {{.SelectedWorktree.Name}}; tmux kill-session -t {{.SelectedWorktree.Name}}"
    loadingText: 'Removing worktree session'
