[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "dotfiles"
path = "~/code/dotfiles"
startup_command = "nvim -c ':Telescope find_files hidden=true'"

[[session]]
name = "brain"
path = "~/Documents/Obsidian Vault"
startup_command = "nvim -c ':ObsidianToday'"
