[default_session]
startup_command = "nvim"

[[session]]
name = "dotfiles"
path = "~/code/dotfiles"

[[session]]
name = "letterpress-main"
path = "~/code/postie/letterpress-app/main"

[[session]]
name = "brain"
path = "~/Documents/Obsidian Vault"
startup_command = "nvim -c ':ObsidianToday'"
