#!/usr/bin/env bash

# Credits: https://github.com/ThePrimeagen/dev

dry="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $*"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $*"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

log "env: $DEV_ENV"

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../utilities/dev-env && pwd)

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

cd "$script_dir" || exit
scripts=$(find "./runs" -perm +111 -type f)

for script in $scripts; do
  basename=$(basename "$script")
  if echo "$script" | grep -qv "$filter"; then
    log "filtering $basename"
    continue
  fi

  execute "$script"
done

# stow -Rnv --dir="$HOME/code/dotfiles" --target="$HOME" .
