#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../utilities/dev-env && pwd)
dry="0"

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $*"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $*"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

cd "$script_dir" || exit
scripts=$(find "./runs" -perm +111 -type f)

for script in $scripts; do
  basename=$(basename "$script")
  if echo "$script" | grep -qv "$filter"; then
    log "filtering $basename"
    continue
  fi

  execute "$script"
done
