#!/usr/bin/env bash

WORK_SESSION=$(tmux list-sessions -F '#{session_name}:#{session_last_attached}' | grep -v '^brain:' | grep -v '^dotfiles:' | sort -t: -k2 -nr | head -n1 | cut -d: -f1); \
if [ -n $WORK_SESSION ]; then
  tmux switch-client -t $WORK_SESSION;
else
  WORK_DIR=$(fd -d 1 -t d --exclude '.*' . ~/code/postie/letterpress-app | sort | head -n 1);
  if [ -n $WORK_DIR ]; then
    SESSION_NAME=$(basename $WORK_DIR);
    tmux new-session -d -s $SESSION_NAME -c $WORK_DIR >/dev/null;
    tmux switch-client -t $SESSION_NAME;
  fi;
fi
