#!/usr/bin/env bash

# Open browser with the port for a worktree (current directory or specified)

worktree_dir=${1:-$PWD}
worktree_name=$(basename "$worktree_dir")

# Generate consistent port based on worktree name
hash=$(echo -n "$worktree_name" | cksum | cut -d' ' -f1)
port=$((3001 + (hash % 999)))

# Open browser with localhost URL
open "http://localhost:$port"