
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
startup_mode = "Maximized"
option_as_alt = "Both"
dynamic_title = false
opacity = 1

[window.padding]
x = 25
y = 20

[font]
size = 20.0
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

[general]
live_config_reload = true
import = ["~/.config/alacritty/theme.toml"]
