[tools]
"gem:rails" = "latest"
"gem:rubocop" = "latest"
"gem:ruby-lsp" = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
go = "latest"
golangci-lint = "latest"
"go:golang.org/x/tools/gopls" = "latest"
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
"npm:@hubspot/cli" = "latest"
"pipx:manim" = "latest"
python = 'latest'
ripgrep = "latest"
ruby = "3.3.8"
starship = "latest"
tree-sitter = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
