[tools]
"gem:rails" = "latest"
"gem:rubocop" = "latest"
"gem:ruby-lsp" = "latest"
lua-language-server = "latest"
node = "latest"
"npm:@hubspot/cli" = "latest"
"pipx:manim" = "latest"
python = 'latest'
ruby = "3.3.8"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
